name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php:
          - 8.1
          - 8.2
        dependencies:
          - locked
          - lowest
          - highest
    name: Tests on PHP ${{ matrix.php }} - ${{ matrix.dependencies }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install tsx
        run: npm install -g tsx
      - uses: shivammathur/setup-php@v2
        # https://github.com/boyney123/github-actions/blob/HEAD/src/actions/setup-php.md
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: '${{ matrix.dependencies }}'
      - name: Test
        run: |
          make test-all
        env:
          TRANSLOADIT_KEY: ${{secrets.TEST_ACCOUNT_KEY}}
          TRANSLOADIT_SECRET: ${{secrets.TEST_ACCOUNT_SECRET}}
          TEST_NODE_PARITY: 1
